export type Member = {
    user_id: string;
    name: string;
    email: string;
};

function dateString(timestampSec: number): string {
    // We need to do this check to see if the timestamp is in milliseconds or
    // seconds. If the timestamp was generated by the Golang backend, we need
    // to multiple by 1000 because it's in seconds. If we generate the
    // timestamp on the frontend, we can skip this check. For context, as of
    // this writing (8/11/21), dividing `Date.now()` by 1000 results in a date
    // in 1975. I picked 2000 as the check point because it's roughly between
    // now and then. This codew ill break on 2/28/31970, so I think we'll be
    // okay.
    if (new Date(timestampSec).getFullYear() < 2000) {
        timestampSec = timestampSec * 1000;
    }

    return new Date(timestampSec).toLocaleString();
}

export { dateString };
