# coding: utf-8

# flake8: noqa
"""
    Aqueduct

    Aqueduct's API endpoint  # noqa: E501

    OpenAPI spec version: 0.2.9
    Contact: support@example.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.general_error import GeneralError
from swagger_client.models.notification_settings import NotificationSettings
from swagger_client.models.notification_settings_inner import NotificationSettingsInner
from swagger_client.models.retention_policy import RetentionPolicy
from swagger_client.models.schedule import Schedule
from swagger_client.models.workflow import Workflow
