apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aqueduct-admin-role-binding
  namespace: aqueduct
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aqueduct-admin-role
