apiVersion: v1
kind: Service
metadata:
  name: {{ include "aqueduct-helm.fullname" . }}
  labels:
    {{- include "aqueduct-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8081
      targetPort: http2
      protocol: TCP
      name: http2
  selector:
    {{- include "aqueduct-helm.selectorLabels" . | nindent 4 }}
