name: Fetch test configurations
description: "Fetches both test-config.yml and test-credentials.yml, the former being configurable."

inputs:
  s3_test_config_path:
    description: "The path in our assets bucket to the test-config.yml file to download."
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-2
        aws-access-key-id: ${{ secrets.KENNY_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.KENNY_AWS_SECRET_ACCESS_KEY }}

    - name: Fetch the Test Config
      shell: bash
      run: aws s3 cp s3://aqueduct-assets/${{ inputs.s3_test_config_path }} ./test-config.yml


