address: <SERVER_ADDRESS>

# A test run will cover the cross-product of each of the sections below.

# OPTIONAL: If set, this can alter the metadata store of the server, so use
# with care.
metadata:
  # If set, we will error if unless the server is in local metadata mode.
  # This ensures that a metadata migration is performed. Otherwise, we allow
  # the server to already be using the appropriate metadata store without any
  # explicit migration action.
  must_migrate: true
  test_s3:

# REQUIRED: All the data integrations to run the test suite against.
# All entries here must be present in `test-credentials.yml`, except
# `aqueduct_demo`, which is built-in.
data:
  aqueduct_demo:
  test_snowflake:
  test_s3:

# REQUIRED: All the compute integrations to run the test suite against.
# All entries here must be present in `test-credentials.yml`, except
# `aqueduct_engine`, which is our native orchestration engine.
compute:
  aqueduct_engine:
