address: <SERVER_ADDRESS>

# A test run will cover the cross-product of each of the sections below.

# OPTIONAL: If set, this can alter the metadata store of the server, so use
# with care.
storage:
  test_s3:
    # If included, will wait until migration is completed before starting the test.
    # Will be ignored if the server is already connected to an resource with the same name.
    use_as_storage:

# REQUIRED: All the data resources to run the test suite against.
# All entries here must be present in `test-credentials.yml`, except
# `aqueduct_demo`, which is built-in.
data:
  aqueduct_demo:
  test_athena:
  test_bigquery:
  test_mariadb:
  test_mongo_db:
  test_mysql:
  test_postgres:
  test_redshift:
  test_s3:
  test_snowflake:
  test_sqlite:

# REQUIRED: All the compute resources to run the test suite against.
# All entries here must be present in `test-credentials.yml`, except
# `aqueduct_engine`, which is our native orchestration engine.
compute:
  aqueduct_engine:
    # aqueduct_engine can have an optional `conda` field to run using conda.
    # It requires `conda`` and `conda-build` pre-installed in testing environment.
    # It does not require an entry in `test-credentials.yml`
    conda:
