linters:
  disable-all: true
  enable:
#    - deadcode
#    - errcheck
    - gosimple
    - staticcheck
    - structcheck

#    - gosec

linters-settings:
  errcheck:
    exclude-functions:
      - defer # these tend to be best effort.

  gosec:
    severity: high
