# Hand-picked from the linters in https://golangci-lint.run/usage/linters
run:
  timeout: 3m
  tests: false
  skip-dirs:
    - .*/tests/*

output:
  sort-results: true

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - staticcheck
    - structcheck
    - unused
    - varcheck
    - bidichk
    - decorder
    - exhaustive
    - makezero
    - nilerr
    - gci
    - goconst
    - goerr113
    - gofmt # has autofixer.
    - gofumpt # has autofixer.
    - goheader
    - goimports # has autofixer.
    - goprintffuncname
    - gosec
    - misspell # has autofixer.
    - prealloc
    - predeclared
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - unparam
    - wastedassign
#    - stylecheck # It would be great to enable this but there are a lot of naming issues right now.
#    - wrapcheck # This would be great to have.


linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  gosec:
    severity: high
