/*
 * Aqueduct
 *
 * Aqueduct's API endpoint
 *
 * API version: 0.2.9
 * Contact: support@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Workflow struct {

	Id string `json:"id"`

	Name string `json:"name"`

	Description string `json:"description,omitempty"`

	Schedule *Schedule `json:"schedule,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	RetentionPolicy *RetentionPolicy `json:"retention_policy,omitempty"`

	NotificationSettings *[]NotificationSettingsInner `json:"notification_settings,omitempty"`
}
