/*
 * Aqueduct
 *
 * Aqueduct's API endpoint
 *
 * API version: 0.2.9
 * Contact: support@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Schedule struct {

	Trigger string `json:"trigger"`

	CronSchedule string `json:"cron_schedule,omitempty"`

	DisableManualTrigger bool `json:"disable_manual_trigger,omitempty"`

	Paused bool `json:"paused,omitempty"`

	SourceId string `json:"source_id,omitempty"`
}
