/*
 * Aqueduct
 *
 * Aqueduct's API endpoint
 *
 * API version: 0.2.9
 * Contact: support@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NotificationSettingsInner struct {

	IntegrationId string `json:"integration_id"`

	NotificationLevel string `json:"notification_level"`
}
