/*
 * Aqueduct
 *
 * Aqueduct's API endpoint
 *
 * API version: 0.2.9
 * Contact: support@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RetentionPolicy struct {

	KLatestRuns int32 `json:"k_latest_runs"`
}
