/*
 * Aqueduct
 *
 * Aqueduct's API endpoint
 *
 * API version: 0.2.9
 * Contact: support@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GeneralError struct {

	Error_ string `json:"error,omitempty"`
}
