name: Periodic Integration Tests

on:
  schedule:
     - cron: '0 15 * * 1-5' # Run at 7AM PST on every weekday
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        concurrency: [ 2, 5 ]

    name: Run Integration Tests with Python Version ${{ matrix.python-version }} Concurrency ${{ matrix.concurrency }}
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-server
        timeout-minutes: 5

      - name: Set up the SDK Integration Tests
        working-directory: integration_tests/sdk
        run: |
          echo "apikey: $(aqueduct apikey)" >> test-config.yml
          echo "address: localhost:8080" >> test-config.yml

      - name: Run the SDK Integration Tests
        timeout-minutes: 30
        working-directory: integration_tests/sdk
        run: python3 run_tests.py -n 5

      - uses: ./.github/actions/upload-artifacts
        if: always()
        with:
          prefix: Aqueduct Engine and DB

      # Notifies Kenny, Suresh.
      - name: Report to Slack on Failure
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notification_title: ''
          message_format: '{emoji} *{workflow}* has {status_message}'
          footer: '{run_url}'
          notify_when: 'failure,warnings'
          mention_users: 'U025MDH5KS6,U04CRDACQMQ'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
