name: Pre-Merge Integration tests

on: 
  pull_request:
    types: [ labeled, opened, synchronize, reopened ]

jobs:
  trigger-integration-tests:
    uses: aqueducthq/aqueduct/.github/workflows/integration-tests.yml@eng-1305-reduce-concurrency-of-tests-to-n=2-to
    if: contains(github.event.pull_request.labels.*.name, 'run_integration_test')