name: Pre-Merge Integration tests

on: 
  pull_request:
    types: [ labeled, opened, synchronize, reopened ]
  merge_group:

jobs:
  trigger-integration-tests:
    if: contains(github.event.pull_request.labels.*.name, 'run_integration_test')
    uses: aqueducthq/aqueduct/.github/workflows/integration-tests.yml@main
    secrets:
      KENNY_AWS_ACCESS_KEY_ID: ${{ secrets.KENNY_AWS_ACCESS_KEY_ID }}
      KENNY_AWS_SECRET_ACCESS_KEY: ${{ secrets.KENNY_AWS_SECRET_ACCESS_KEY }}

  another-job:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Only run these steps if in the merge group.
        if: ${{ github.event_name != 'pull_request' }}
        uses: aqueducthq/aqueduct/.github/workflows/integration-tests.yml@main
        secrets:
          KENNY_AWS_ACCESS_KEY_ID: ${{ secrets.KENNY_AWS_ACCESS_KEY_ID }}
          KENNY_AWS_SECRET_ACCESS_KEY: ${{ secrets.KENNY_AWS_SECRET_ACCESS_KEY }}