name: Pre-Merge Integration tests

on:
  push:
    branches:
      - cgwu_dummy_branch
  pull_request:
    types: [labeled, opened, synchronize, reopened]

jobs:
  trigger-integration-tests:
    if: contains(github.event.pull_request.labels.*.name, 'run_integration_test')
    uses: aqueducthq/aqueduct/.github/workflows/integration-tests.yml@main
    secrets:
      KENNY_AWS_ACCESS_KEY_ID: ${{ secrets.KENNY_AWS_ACCESS_KEY_ID }}
      KENNY_AWS_SECRET_ACCESS_KEY: ${{ secrets.KENNY_AWS_SECRET_ACCESS_KEY }}
