# This is a workaround due to Github Actions limitations on aggregating results from a job matrix.

name: Skipped Integration Tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    name: All Integration Tests with Basic Config
    steps:
      - run: |
          exit 0