name: Skip Pre-Merge Integration tests

on: 
  pull_request:
    types: [ labeled, opened, synchronize, reopened ]
    paths-ignore:
      - 'src/golang/**'
      - 'src/python/**'
      - 'integration_tests/**'
      - 'sdk/aqueduct/**'
      - '.github/workflows/integration-tests.yml'

jobs:
  trigger-integration-tests:
    uses: aqueducthq/aqueduct/.github/workflows/integration-tests.yml@eng-1306-remove-need-to-run-tests-on-non-code
    with:
      run-integration-test: false
    