# This is a workaround due to Github Actions limitations on aggregating results from a job matrix.

name: Skipped Integration Tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  run-tests-basic:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    name: All Integration Tests with Basic Config
    steps:
      - run: |
          exit 0

  run-tests-s3-storage:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: SDK Integration Tests with S3 Storage Layer
    steps:
      - run: |
          exit 0

  run-tests-data-integrations:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: SDK Data Integration Tests
    steps:
      - run: |
          exit 0          
            
