name: Skip Pre-Merge BaseResource tests

on: 
  pull_request:
    types: [ labeled, opened, synchronize, reopened ]

jobs:
  trigger-integration-tests:
    if: contains(github.event.pull_request.labels.*.name, 'skip_integration_test')
    uses: aqueducthq/aqueduct/.github/workflows/skipped-integration-tests.yml@main