name: UI Build

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/ui/**'
      - '.github/workflows/ui-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Format check common
        working-directory: ./src/ui/common
        run: npm run lint

      - name: Format check app
        working-directory: ./src/ui/app
        run: npm run lint

      - name: Link common
        working-directory: ./src/ui
        run: make link-dev

      - name: Install dependencies
        working-directory: ./src/ui/app
        run: npm install

      - name: Make dist
        working-directory: ./src/ui
        run: make dist
