name: UI Build

on:
  push:
    branches: [ eng-1185-add-automated-ui-build-github-action-to ] # TODO: REMOVE
  pull_request:
    branches: [ main ]
    paths:
      - 'src/ui/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

#      - name: Install dependencies
#        working-directory: ./src/ui/app
#        run: npm install

      - name: Format check
        working-directory: ./src/ui/app
        run: npm run lint

      - name: Build
        working-directory: ./src/ui
        run: make build
