name: Backend Unit Tests

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/golang/**'

jobs:
  test:
    name: Run Backend Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.1

      - name: Turn on GO111MODULE
        run: go env -w GO111MODULE=on

      - name: Run Tests
        working-directory: ./src
        run: make test